rename table field
kuzudb/explorer pull request #53
Opened 2023-11-22 21:41 UTC by Ashleyhx

2023-11-28 01:13 UTC, Ashleyhx commented
Able to rename table from SchemaView, graph, and settingsView will change accordingly.
![image](https://github.com/kuzudb/explorer/assets/84025279/2fb1a5e7-670c-4280-9433-9f9de3cabd24)
![image](https://github.com/kuzudb/explorer/assets/84025279/9a56246f-d728-453b-906a-829034b570f1)
![image](https://github.com/kuzudb/explorer/assets/84025279/bcbeab03-b5de-4634-bcd9-ce5bf39d74d4)

2023-11-28 10:31 UTC, mewim commented on src/components/SchemaView/SchemaSidebarEditView.vue
> +      this.renameTable = true;
You should not require this bool.

2023-11-28 10:33 UTC, mewim commented on src/components/SchemaView/SchemaSidebarEditView.vue
> +      if (this.currLabel === this.label) {
This should not be required either. If the name does not change, you do not need to show the buttons (which means this is not possible).

2023-11-28 10:34 UTC, mewim commented on src/components/SchemaView/SchemaSidebarEditView.vue
> +        <button v-if="renameTable" @click="saveNewTableName" class="btn btn-sm btn-outline-primary">
The buttons can simply be shown / hidden by comparing if `currLabel === label"

2023-11-28 10:37 UTC, mewim commented on src/components/SchemaView/SchemaViewMain.vue
> +      this.settingsStore.renameNodeTable(oldLabel, newLabel);
This should not be done. Instead, you should follow the approach of `updatePlaceholderNodeTableLabel`.

2023-11-28 10:37 UTC, mewim commented on src/components/SchemaView/SchemaSidebarEditView.vue
> +        &nbsp; Table: &nbsp;
This label can be removed I think

2023-11-28 10:39 UTC, mewim commented on kuzu
Discard submodule change

2023-11-28 10:42 UTC, mewim commented
> Able to rename table from SchemaView, graph, and settingsView will change accordingly. ![image](https://private-user-images.githubusercontent.com/84025279/286077324-2fb1a5e7-670c-4280-9433-9f9de3cabd24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjgyOTAsIm5iZiI6MTcwMTE2Nzk5MCwicGF0aCI6Ii84NDAyNTI3OS8yODYwNzczMjQtMmZiMWE1ZTctNjcwYy00MjgwLTk0MzMtOWY5ZGUzY2FiZDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YzhlYWYzM2Y5ODJhYmM0NjVkZjgxOTgyOTI5ZTJkMThhNTIzYzBjMTFkODZjYmZhZWQ4NDg4MTJhNmVlNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ONj2LCABBQEoT6LV6ihzvuEklqDfnR3p3BTxny82_xg) ![image](https://private-user-images.githubusercontent.com/84025279/286077767-9a56246f-d728-453b-906a-829034b570f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjgyOTAsIm5iZiI6MTcwMTE2Nzk5MCwicGF0aCI6Ii84NDAyNTI3OS8yODYwNzc3NjctOWE1NjI0NmYtZDcyOC00NTNiLTkwNmEtODI5MDM0YjU3MGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNGMwY2E5YWJlMjYyMTRjZTlhOTIxYjEyY2EzYWI1NDNiYmE0NTQ5NTdhZWJkODYxMDJmYmZlMzUzMWQyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RCypzin-6hhn1NmljSLL5EEf0pzIgXp0m4kd1462Lpo) ![image](https://private-user-images.githubusercontent.com/84025279/286077839-bcbeab03-b5de-4634-bcd9-ce5bf39d74d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjgyOTAsIm5iZiI6MTcwMTE2Nzk5MCwicGF0aCI6Ii84NDAyNTI3OS8yODYwNzc4MzktYmNiZWFiMDMtYjVkZS00NjM0LWJjZDktY2U1YmYzOWQ3NGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwMzk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NWY0YWI2YjBjNDFhYmM0ODY1NDFjNWVhYzQ0YWJmY2ZiZmQ5ZTM4YTA2OGM2ZmE0NmQ4NzAzYTk5Yjk3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o0FdR4ySVR1SRhsbcDHP8DOFw4IDnnq5f4WVtSBfd3g)

The behavior as shown in 1st screenshot is incorrect. The table input has been changed to `cc` yet the diagram is showing `City` still.

Also, you should improve the visual style:
1. Align the buttons and the input
2. Take full space
3. Adjust button spacing

2023-11-28 10:44 UTC, mewim commented
Also, maybe I missed something? You used `updatePlaceholderRelTable` but did not mark any table as a placeholder to begin with, so this might work just as a coincidence.

2023-11-28 10:44 UTC, mewim requested changes
See my comments

2023-12-01 09:09 UTC, mewim commented on src/utils/Constants.js
> +export const PLACEHOLDER_REL_TABLE = "__placeholder_rel_table__";
You should not remove the new line here.

2023-12-01 09:10 UTC, mewim commented on src/utils/DataDefinitionLanguage.js
> +  saveRenamedNodeTable(oldName, newName) {
The two functions below should be merged. Also, it should just be `renameTable`.

2023-12-01 09:12 UTC, mewim commented on src/components/SchemaView/SchemaSidebarEditView.vue
> +    saveNewTableName() {
This could be simplified:
```
this.$nextTick(() => {
  this.$emit(this.isNode ? "saveRenamedNodeTable" : "saveRenamedRelTable", this.label, this.currLabel);
});
```

2023-12-01 09:12 UTC, mewim commented on src/components/SchemaView/SchemaSidebarEditView.vue
> +    saveNewTableName() {
Also, the event name can be simplified as `renameNodeTable` and `renamedRelTable `

2023-12-01 09:13 UTC, mewim commented on src/components/SchemaView/SchemaViewMain.vue
> +    enterRenameNodeTableMode(newTableName) {
If the code here is not being used, you should remove the code instead of commenting out

2023-12-02 06:11 UTC, merged